// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.

var findTheDifference = function(s, t) {
    var checker = false;
    for(var i=0; i<t.length; i++){
        for(var j=0; j<s.length; j++){
            if(t[i] === s[j]){
                checker = true;
            }
        }
        if(checker === false){
            console.log(t[i]);
            return t[i];
        }
        checker = false;
    }
};

findTheDifference("abcd", "abcde");
findTheDifference("abcd", "abicd");
findTheDifference("a", "aa");
